CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "AspNetRoles" (
    id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE "AspNetUsers" (
    id text NOT NULL,
    app_user_id integer NOT NULL,
    first_name text,
    last_name text,
    sign_up_date timestamp without time zone NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE clients (
    id character varying(128) NOT NULL,
    secret text NOT NULL,
    name character varying(100) NOT NULL,
    application_type integer NOT NULL,
    active boolean NOT NULL,
    refresh_token_life_time integer NOT NULL,
    access_token_life_time integer NOT NULL,
    allowed_origin character varying(100),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE history_row (
    migration_id text NOT NULL,
    productversion text NOT NULL,
    CONSTRAINT pk_history_row PRIMARY KEY (migration_id)
);

CREATE TABLE refresh_tokens (
    id text NOT NULL,
    subject character varying(50) NOT NULL,
    client_id character varying(50) NOT NULL,
    issued_utc timestamp without time zone NOT NULL,
    expires_utc timestamp without time zone NOT NULL,
    protected_ticket text NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoleClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE app_users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    image_id integer,
    email text NOT NULL,
    phone_number text NOT NULL,
    last_time_sent timestamp without time zone,
    is_deleted boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    created_by text,
    last_modified timestamp with time zone NOT NULL,
    last_modified_by text,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE files (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    path text NOT NULL,
    size bigint NOT NULL,
    owner_id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    created_by text,
    last_modified timestamp with time zone NOT NULL,
    last_modified_by text,
    CONSTRAINT pk_files PRIMARY KEY (id),
    CONSTRAINT fk_files_app_users_owner_id FOREIGN KEY (owner_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_app_users_image_id ON app_users (image_id);

CREATE INDEX ix_asp_net_role_claims_role_id ON "AspNetRoleClaims" (role_id);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON "AspNetUserClaims" (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON "AspNetUserLogins" (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON "AspNetUserRoles" (role_id);

CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalized_user_name);

CREATE INDEX ix_files_owner_id ON files (owner_id);

ALTER TABLE app_users ADD CONSTRAINT fk_app_users_files_image_id FOREIGN KEY (image_id) REFERENCES files (id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20240408175424_InitialMigration', '8.0.2');

COMMIT;

