version: '3.4'

services:


  dbup:
    image: ${DOCKER_REGISTRY-}dbup
    build:
      context: .
      dockerfile: DbUp/Dockerfile
    restart: "no"
    volumes:
     - C:\Users\The Effrontery\.aws\credentials:/home/app/.aws/credentials:ro

  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - solr
      - rabbitmq
      - dbup
    volumes:
     - C:\Users\The Effrontery\.aws\credentials:/home/app/.aws/credentials:ro

  queueapp:
    image: ${DOCKER_REGISTRY-}queueapp
    build:
      context: .
      dockerfile: QueueApp/Dockerfile
    depends_on:
      - solr
      - rabbitmq
      - dbup
    volumes:
     - C:\Users\The Effrontery\.aws\credentials:/home/app/.aws/credentials:ro
  solr:
    image: solr
    command:
      - solr-precreate
      - default_core
    volumes:
      - ./solrdata:/var/solr
    ports:
      - "8983:8983"
    depends_on:
      - dbup

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      - dbup



